-- =====================================================
-- AdventureWorks SQL EDA Project
-- Author: Sameer
-- Database: MySQL
-- =====================================================

/* ===============================
   BASIC DATA EXPLORATION
   =============================== */

-- 1. List all distinct customer countries
SELECT DISTINCT country
FROM dim_customer
ORDER BY country;

-- 2. List all product categories, subcategories, and products
SELECT DISTINCT 
    pc.category_name,
    ps.subcategory_name,
    p.product_name
FROM dim_product p
JOIN dim_product_subcategory ps 
    ON p.product_subcategory_key = ps.product_subcategory_key
JOIN dim_product_category pc 
    ON ps.product_category_key = pc.product_category_key
ORDER BY 1, 2, 3;


/* ===============================
   DATE RANGE & CUSTOMER AGE
   =============================== */

-- 3. First order date, last order date, and number of days between them
SELECT 
    MIN(order_date) AS first_order_date,
    MAX(order_date) AS last_order_date,
    DATEDIFF(MAX(order_date), MIN(order_date)) AS date_difference_days
FROM fact_sales;

-- 4. Youngest and oldest customer by birthdate
SELECT 
    MIN(birth_date) AS oldest_birthdate,
    MAX(birth_date) AS youngest_birthdate
FROM dim_customer;


/* ===============================
   BASIC SALES METRICS
   =============================== */

-- 5. Total sales revenue
SELECT 
    SUM(fs.order_quantity * p.product_price) AS total_sales
FROM fact_sales fs
JOIN dim_product p 
    ON fs.product_key = p.product_key;

-- 6. Total quantity sold
SELECT 
    SUM(order_quantity) AS total_quantity_sold
FROM fact_sales;

-- 7. Average selling price
SELECT 
    AVG(p.product_price) AS avg_selling_price
FROM fact_sales fs
JOIN dim_product p 
    ON fs.product_key = p.product_key;


/* ===============================
   COUNTS & VOLUMES
   =============================== */

-- 8. Total number of products
SELECT 
    COUNT(DISTINCT product_key) AS total_products
FROM dim_product;

-- 9. Total number of customers
SELECT 
    COUNT(customer_key) AS total_customers
FROM dim_customer;

-- 10. Total orders and distinct orders
SELECT 
    COUNT(order_number) AS total_order_rows,
    COUNT(DISTINCT order_number) AS distinct_orders
FROM fact_sales;

-- 11. Customers who placed at least one order
SELECT 
    COUNT(DISTINCT customer_key) AS active_customers
FROM fact_sales;


/* ===============================
   CATEGORY & PRODUCT ANALYSIS
   =============================== */

-- 12. Average product cost per category
SELECT 
    pc.category_name,
    AVG(p.product_cost) AS avg_product_cost
FROM dim_product p
JOIN dim_product_subcategory ps 
    ON p.product_subcategory_key = ps.product_subcategory_key
JOIN dim_product_category pc 
    ON ps.product_category_key = pc.product_category_key
GROUP BY pc.category_name
ORDER BY avg_product_cost DESC;

-- 13. Total products by category
SELECT 
    pc.category_name,
    COUNT(p.product_key) AS total_products
FROM dim_product p
JOIN dim_product_subcategory ps 
    ON p.product_subcategory_key = ps.product_subcategory_key
JOIN dim_product_category pc 
    ON ps.product_category_key = pc.product_category_key
GROUP BY pc.category_name
ORDER BY total_products DESC;

-- 14. Total revenue by product category
SELECT 
    pc.category_name,
    SUM(fs.order_quantity * p.product_price) AS total_revenue
FROM fact_sales fs
JOIN dim_product p 
    ON fs.product_key = p.product_key
JOIN dim_product_subcategory ps 
    ON p.product_subcategory_key = ps.product_subcategory_key
JOIN dim_product_category pc 
    ON ps.product_category_key = pc.product_category_key
GROUP BY pc.category_name
ORDER BY total_revenue DESC;


/* ===============================
   CUSTOMER & REGION PERFORMANCE
   =============================== */

-- 15. Total revenue generated by each customer
SELECT 
    c.customer_key,
    CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
    SUM(fs.order_quantity * p.product_price) AS total_revenue
FROM fact_sales fs
JOIN dim_customer c 
    ON fs.customer_key = c.customer_key
JOIN dim_product p 
    ON fs.product_key = p.product_key
GROUP BY c.customer_key, customer_name
ORDER BY total_revenue DESC;

-- 16. Revenue by region
SELECT 
    t.region,
    SUM(fs.order_quantity * p.product_price) AS total_sales
FROM fact_sales fs
JOIN dim_territory t 
    ON fs.territory_key = t.territory_key
JOIN dim_product p 
    ON fs.product_key = p.product_key
GROUP BY t.region
ORDER BY total_sales DESC;


/* ===============================
   RANKING & TOP PERFORMERS
   =============================== */

-- 17. Top 5 products by revenue
SELECT 
    p.product_name,
    SUM(fs.order_quantity * p.product_price) AS total_revenue
FROM fact_sales fs
JOIN dim_product p 
    ON fs.product_key = p.product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC
LIMIT 5;

-- 18. Bottom 5 products by revenue
SELECT 
    p.product_name,
    SUM(fs.order_quantity * p.product_price) AS total_revenue
FROM fact_sales fs
JOIN dim_product p 
    ON fs.product_key = p.product_key
GROUP BY p.product_name
ORDER BY total_revenue ASC
LIMIT 5;

-- 19. Top 5 subcategories by revenue
SELECT 
    ps.subcategory_name,
    SUM(fs.order_quantity * p.product_price) AS total_revenue
FROM fact_sales fs
JOIN dim_product p 
    ON fs.product_key = p.product_key
JOIN dim_product_subcategory ps 
    ON p.product_subcategory_key = ps.product_subcategory_key
GROUP BY ps.subcategory_name
ORDER BY total_revenue DESC
LIMIT 5;

-- 20. Top 10 customers by revenue
SELECT 
    c.customer_key,
    CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
    SUM(fs.order_quantity * p.product_price) AS total_revenue
FROM fact_sales fs
JOIN dim_customer c 
    ON fs.customer_key = c.customer_key
JOIN dim_product p 
    ON fs.product_key = p.product_key
GROUP BY c.customer_key, customer_name
ORDER BY total_revenue DESC
LIMIT 10;
